name: Generate Jar

on:
  push:
    branches:
      - main # You can change this to your desired branch
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Validate, build and run tests
      run: mvn --batch-mode --update-snapshots verify
    - name: Build .jar
      run: mkdir jarFiles && cp target/*jar jarFiles
    - name: Commit and Push jar files
      run: |
        git status
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add jarFiles
        git commit -m "Generate jar files"
        git push
  
  
