name: docs

on:
  push:
    branches: [ master ]
    paths: [ '**.java', '.github/workflows/docs.yml' ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Checkout the gh-pages branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: gh-pages
        path: gh-pages

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build docs with Maven
      run: mvn javadoc:javadoc
