name: Generate Javadoc

on:
  push:
    branches:
      - main # You can change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Change to your desired Java version
        distribution: 'adopt'

    - name: Build and Generate Javadoc
      run: |
        ls -la src
        # Compile your Java code
        javac -d target/classes src/*.java
        
        # Generate Javadoc
        javadoc -d target/docs -sourcepath src -subpackages main
        
        # Create a README file with a link to the generated Javadoc
        echo "Generated Javadoc: [Link](./target/docs/index.html)" >> test.txt

    - name: Commit and Push Javadoc
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add target/docs
        git commit -m "Generate Javadoc"
        git push

