name: Generate Javadoc

on:
  push:
    branches:
      - main # You can change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Change to your desired Java version
        distribution: 'adopt'

    - name: Build and Generate Javadoc
      run: |
        # Build your Maven project and generate Javadoc
        mvn clean package javadoc:javadoc
    - name: Build and Generate Javadoc
      run: 
        ls target
    - name: Build and Generate Javadoc
      run: 
        mv target package

    - name: Commit and Push Javadoc
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add package
        git commit -m "Generate Javadoc"
        git push
