name: docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Checkout the javadoc branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: javadoc
        path: javadoc

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build docs with Maven
      run: mvn javadoc:javadoc
