name: Generate Javadoc

on:
  push:
    branches:
      - main # You can change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Change to your desired Java version
        distribution: 'adopt'

    - name: Build and Generate Javadoc
      run: |
        # Build your Maven project and generate Javadoc
        mvn clean package javadoc:javadoc
        mv target documentation
        
    - name: Commit and Push Javadoc
      run: 
        git config user.name "GitHub Actions"
    - name: Commit and Push Javadoc
      run: 
        git config user.email "actions@github.com"
    - name: Commit and Push Javadoc
      run: 
        git add documentation

    - name: Commit and Push Javadoc
      run: 
        git commit -m "Generate Javadoc"
    - name: Commit and Push Javadoc
      run: 
        git push
